name: Build and Deploy to GHCR

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch support)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set lowercase repository owner
        run: |
          echo "REPO_OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Extract version info
        id: version
        run: |
          TAG=${{ github.event.release.tag_name }}
          SHA_SHORT=$(git rev-parse --short HEAD)
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "SHA_SHORT=$SHA_SHORT" >> $GITHUB_ENV

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LOWER }}/csnadeclassifier:${{ env.TAG }}
            ghcr.io/${{ env.REPO_OWNER_LOWER }}/csnadeclassifier:latest
            ghcr.io/${{ env.REPO_OWNER_LOWER }}/csnadeclassifier:${{ env.TAG }}-${{ env.SHA_SHORT }}
          secrets: |
            "bot_token=${{ secrets.BOT_TOKEN }}"
            "gemini_api_key=${{ secrets.GEMINI_API_KEY }}"
