name: Build and Deploy to GHCR

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch support)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract version info
        id: version
        run: |
          TAG=${{ github.event.release.tag_name }}
          SHA_SHORT=$(git rev-parse --short HEAD)
          REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "SHA_SHORT=$SHA_SHORT" >> $GITHUB_ENV
          echo "REPO_OWNER_LOWER=$REPO_OWNER_LOWER" >> $GITHUB_ENV
      
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LOWER }}/csnadeclassifier:${{ env.TAG }}
            ghcr.io/${{ env.REPO_OWNER_LOWER }}/csnadeclassifier:latest
            ghcr.io/${{ env.REPO_OWNER_LOWER }}/csnadeclassifier:${{ env.TAG }}-${{ env.SHA_SHORT }}
      
      - name: Deploy with Docker Compose
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          docker compose up -d
